name: weather_app
description: Приложение "Погода в кармане"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  http: ^1.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.1.0
  workmanager: ^0.5.2
  timezone: ^0.10.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true